INSERT INTO questions (quiz_id, question, option_A, option_B, option_C, option_D, answer, explanation)
VALUES
    (1, 'Ile możliwych adresów IPv4 istnieje?', 'Około 1,3 miliona', 'Około 3 miliony', 'Około 23 miliony', 'Ponad 4 miliardy', 'D', 'IPv4 ma ponad 4 miliardy adresów, ponieważ składa się z 32-bitowych numerów, co daje 2 do potęgi 32 różnych kombinacji adresów.'),
    (1, 'Jaki jest standardowy rozmiar nagłówka w IPv4?', '20 bajtów', '40 bajtów', '60 bajtów', '80 bajtów', 'A', 'Standardowy rozmiar nagłówka IPv4 wynosi 20 bajtów.'),
    (1, 'Co reprezentuje adres IPv4 127.0.0.1?', 'Adres routera', 'Adres broadcastowy', 'Adres lokalnej pętli zwrotnej', 'Publiczny adres IP', 'C', 'Adres 127.0.0.1 w IPv4 to adres lokalnej pętli zwrotnej, używany do testowania komunikacji w obrębie własnego systemu.'),
    (1, 'Ile bitów ma adres IPv6?', '32 bity', '64 bity', '128 bitów', '256 bitów', 'C', 'IPv6 używa adresów 128-bitowych, co znacząco zwiększa pulę dostępnych adresów w porównaniu do IPv4.'),
    (1, 'Jaka jest główna zaleta IPv6 w porównaniu do IPv4?', 'Szybszy transfer danych', 'Mniejszy rozmiar adresu', 'Większa pula adresów', 'Lepsza kompatybilność z starszymi systemami', 'C', 'Główną zaletą IPv6 jest znacznie większa pula adresów, umożliwiająca przydzielenie unikalnego adresu praktycznie każdemu urządzeniu.'),
    (1, 'Co oznacza "IPv4" w adresie IP?', 'Internet Protocol Vision 4', 'Internet Protocol Version 4', 'Internal Protocol Version 4', 'International Protocol Vision 4', 'B', 'IPv4 to skrót od Internet Protocol Version 4, czyli czwartej wersji protokołu internetowego.'),
    (1, 'Jaką klasą adresów IPv4 jest adres zaczynający się od 192?', 'Klasa A', 'Klasa B', 'Klasa C', 'Klasa D', 'C', 'Adresy zaczynające się od 192 należą do klasy C w modelu klasowym adresacji IPv4.'),
    (1, 'Która część adresu IPv6 jest używana do identyfikacji sieci?', 'Pierwsze 32 bity', 'Pierwsze 48 bitów', 'Pierwsze 64 bity', 'Pierwsze 96 bitów', 'C', 'W adresie IPv6, pierwsze 64 bity są zazwyczaj używane do identyfikacji sieci.'),
    (1, 'Jakie jest główne zastosowanie adresów IPv4 typu multicast?', 'Komunikacja jeden-do-jednego', 'Komunikacja jeden-do-wielu', 'Komunikacja wielu-do-wielu', 'Komunikacja wielu-do-jednego', 'B', 'Adresy multicast w IPv4 są używane do komunikacji jeden-do-wielu.'),
    (1, 'Czym jest "tunelowanie" w kontekście IPv6?', 'Metodą szyfrowania danych', 'Techniką zwiększania prędkości transmisji', 'Sposobem na przesyłanie danych IPv6 przez sieci IPv4', 'Techniką redukcji rozmiaru pakietów', 'C', 'Tunelowanie to technika umożliwiająca przesyłanie danych IPv6 przez istniejące sieci IPv4.'),
    (1, 'Który z poniższych adresów jest przykładem adresu prywatnego w IPv4?', '172.16.0.1', '172.32.0.1', '192.168.1.1', 'Obie odpowiedzi A i C', 'D', '172.16.0.1 i 192.168.1.1 to przykłady prywatnych adresów IPv4.'),
    (1, 'Która z poniższych opcji jest cechą charakterystyczną IPv6?', 'Nagłówek o stałej długości', 'Adresy IP o długości 32 bitów', 'Wymóg stosowania NAT', 'Klasowy system adresacji', 'A', 'IPv6 ma nagłówek o stałej długości, co ułatwia przetwarzanie przez routery.'),
    (1, 'Jak nazywa się technika pozwalająca na współistnienie IPv4 i IPv6?', 'Dual Stack', 'IP switching', 'IP translation', 'IP modification', 'A', 'Technika Dual Stack umożliwia urządzeniom obsługę zarówno IPv4, jak i IPv6 jednocześnie.'),
    (1, 'Jaki jest główny cel stosowania NAT (Network Address Translation) w IPv4?', 'Zwiększenie prędkości internetu', 'Przetwarzanie adresów IPv6', 'Oszczędzanie publicznych adresów IP', 'Blokuje ruch sieciowy', 'C', 'NAT jest używany w IPv4 głównie do oszczędzania publicznych adresów IP poprzez umożliwienie wielu urządzeniom korzystania z jednego adresu.'),
    (1, 'Która z poniższych opcji nie jest typem rekordu w DNS dla IPv6?', 'AAAA', 'A', 'PTR', 'CNAME', 'B', 'Rekord A jest używany dla adresów IPv4, podczas gdy AAAA jest używany dla IPv6.')
;
